### ISSUE TITLE
What is package/generated-react?

### ISSUE THREAD

**Issue by bufdev** [connectrpc/connect-query-es#11]
Is this an example? We should make this consistent with connect-web/protobuf-es

**Comment by dimitropoulos** [comment]
It's not an example: it's code used for tests in the other packages in this repo.  Connect-web doesn't have unit tests which test input-output directly, and this repo does -> that's the reason for the difference.

@timostamm and I spoke this morning about how we can "inline" some of the generated output that this file provides, so I expect that will be one of the next things happening in the project structure.

**Comment by timostamm** [comment]
@paul-sachs, if the plan is to have just one example, would that example be easier to follow if it generated code itself?

Generating into an intermediate package certainly has benefits for a large monorepo where multiple packages consume the same generated code, but it seems a bit much for a basic example...

`generated-react` is used in tests in @connectrpc/connect-query, but only code generated by protoc-gen-es and protoc-gen-connect-es. In similar cases, we just define the service ourselves in connect-es ([example](https://github.com/connectrpc/connect-es/blob/22e52787849044f37c6fcb35d6ebc84c4bd589ac/packages/connect/src/protocol-grpc/handler-factory.spec.ts#L34-L50)). Having separate proto files for tests and generating them in connect-query should also work well.

**Comment by paul-sachs** [comment]
@timostamm I agree, especially with recent work untangling circular dependency. I can work to remove this entirely.
