### ISSUE TITLE
ERR_INVALID_HTTP_RESPONSE when trying to connect to grpc server

### ISSUE THREAD

**Issue by thatsnoi** [connectrpc/connect-query-es#123]
I am having the exact same issue as this person on SO: https://stackoverflow.com/questions/76871048/err-invalid-http-response-using-bufbuild-connect-to-connect-to-a-python-grpcio

How can I fix this?

**Comment by thatsnoi** [comment]
Reposted here https://github.com/connectrpc/connect-es/issues/785 with some more context

**Comment by srikrsna-buf** [comment]
Replied in https://github.com/connectrpc/connect-es/issues/785#issuecomment-1695030323
