### ISSUE TITLE
disableQuery unique symbol stopping typescript declaration

### ISSUE THREAD

**Issue by mckelveygreg** [connectrpc/connect-query-es#209]
We use this lib to publish a client to npm that our different code bases can share. However, there seems to be issues I can't figure out surrounding `unique symbol`'s and typescript declaration. 

I noticed you have an exception for this case in your eslint, and it is for a test file to consume the generated lib. 
Do you know of a work around beyond having an unused `disableQuery` import everywhere I'd want to use the generated code?

**Comment by mckelveygreg** [comment]
Found a fix!

**Comment by paul-sachs** [comment]
I'm glad you were able to find the fix. We've been trying to remove the deep hooks to React and this seems to have been caused there. I'll also want to add a test so this doesn't happen again.

**Comment by paul-sachs** [comment]
Released in v0.5.2 🚀
