### ISSUE TITLE
Support/documentation for stream processing with tanstack

### ISSUE THREAD

**Issue by 0xAlcibiades** [connectrpc/connect-query-es#225]
**Is your feature request related to a problem? Please describe.**
Right now tanstack docs for connect-web talk about unary requests, which isn't the big unlock that gRPC/connect provides.

**Describe the solution you'd like**
What would you like to have `connect-es` do? How should we solve the problem?

connect-es should have documentation/examples/support for async stream processing with tanstack

Please specify whether the request is for Connect for Web or Connect for
Node.js.

Web

**Describe alternatives you've considered**
If you've proposed a solution, are there any alternatives? Why are they worse
than your preferred approach?

Manual stream processing

**Comment by paul-sachs** [comment]
We try to address the streaming question in the [readme](https://github.com/connectrpc/connect-query-es#what-about-streaming). It largely comes down to @tanstack/react-query itself not having primitives to deal with streaming, it felt odd for `connect-query-es` to deal with it. With the migration to v1, it's actually quite easy to build your own opinionated streaming API, using whatever primitives you want (web sockets, web transport, etc). We've played around with a few implementations using `react-query` but it's never felt polished enough to publish. There are also different varieties of streaming (do we keep all the streamed data or just the last, etc) that change the shape of the cached data quite a bit.

All this to say is that we'd love to see some user space implementations (and requirements) before committing to an API.

**Comment by paul-sachs** [comment]
For an example of what that looks like, this is the v1 version of something that **might** work:

```tsx
import type {
  Message,
  MethodInfoServerStreaming,
  PartialMessage,
  ServiceType,
} from "@bufbuild/protobuf";
import type {
  CallOptions,
  ConnectError,
  StreamResponse,
  Transport,
} from "@connectrpc/connect";
import { createAsyncIterable } from "@connectrpc/connect/protocol";
import type { UseQueryOptions } from "@tanstack/react-query";
import { useQuery, useQueryClient } from "@tanstack/react-query";

import {
  useTransport,
  type ConnectQueryKey,
  createConnectQueryKey,
} from "@connectrpc/connect-query";

export type MethodServerStreamingDescriptor<
  I extends Message<I>,
  O extends Message<O>,
> = MethodInfoServerStreaming<I, O> & {
  readonly service: Omit<ServiceType, "methods">;
};

export interface StreamResponseMessage<O> {
  /** List of responses in chronological order */
  responses: O[];
  /** Indicates if the stream is completed or not. */
  done: boolean;
}

function handleStreamResponse<I extends Message<I>, O extends Message<O>>(
  stream: Promise<StreamResponse<I, O>>,
  options?: CallOptions
): AsyncIterable<O> {
  const it = (async function* () {
    const response = await stream;
    options?.onHeader?.(response.header);
    yield* response.message;
    options?.onTrailer?.(response.trailer);
  })()[Symbol.asyncIterator]();
  return {
    [Symbol.asyncIterator]: () => ({
      next: () => it.next(),
    }),
  };
}

type CreateServerStreamingQueryOptions<
  I extends Message<I>,
  O extends Message<O>,
  SelectOutData = StreamResponseMessage<O>,
> = {
  transport: Transport;
  callOptions?: Omit<CallOptions, "signal"> | undefined;
} & Omit<
  UseQueryOptions<
    StreamResponseMessage<O>,
    ConnectError,
    SelectOutData,
    ConnectQueryKey<I>
  >,
  "queryFn" | "queryKey"
>;

export function useServerStreamingQuery<
  I extends Message<I>,
  O extends Message<O>,
  SelectOutData = StreamResponseMessage<O>,
>(
  methodSig: MethodServerStreamingDescriptor<I, O>,
  input: PartialMessage<I> | undefined,
  {
    transport,
    callOptions,
    ...queryOptions
  }: Omit<
    CreateServerStreamingQueryOptions<I, O, SelectOutData>,
    "transport"
  > & {
    transport?: Transport;
  } = {}
) {
  const ctxTransport = useTransport();
  const finalTransport = transport ?? ctxTransport;
  const queryClient = useQueryClient();
  const queryKey = createConnectQueryKey(methodSig, input);
  return useQuery({
    ...queryOptions,
    queryKey,
    queryFn: async ({ signal }) => {
      let responses: O[] = [];
      for await (const response of handleStreamResponse(
        finalTransport.stream<I, O>(
          {
            typeName: methodSig.service.typeName,
            methods: {},
          },
          methodSig,
          signal,
          callOptions?.timeoutMs,
          callOptions?.headers,
          createAsyncIterable([input ?? {}])
        )
      )) {
        // Spreading results to keep referential integrity for changes
        responses = [...responses, response];
        const newData: StreamResponseMessage<O> = {
          done: false,
          responses,
        };
        queryClient.setQueriesData({ queryKey }, newData);
      }
      return {
        done: true,
        responses,
      } satisfies StreamResponseMessage<O>;
    },
  });
}
```

This code is a modified version of something we've had bouncing around internally, but hasn't been field tested well enough.

**Comment by paul-sachs** [comment]
@0xAlcibiades I hope that example helps a little.

**Comment by 0xAlcibiades** [comment]
Yep, I think @nickadamson arrived at a similar conclusion here: https://github.com/valorem-labs-inc/react-hooks/blob/main/src/hooks/useStream.ts

**Comment by paul-sachs** [comment]
Ah interesting. In that case it's just using react-query as a way to broadcast the result to anyone using the same queryKey. Yeah that is definitely one way to do it. I'd have to dig in to fully groc the details, I suspect that example handles cancellation a little more consistently compared to mine, which just relies the on default behaviour for react-query, which as mentioned, doesn't really provide the API required for understanding the state of a stream.

**Comment by paul-sachs** [comment]
Closing this. If we come up with a more battle tested stream API, we'll readdress the documentation issue.
