### ISSUE TITLE
How to get query key?

### ISSUE THREAD

**Issue by Nikola-Milovic** [connectrpc/connect-query-es#269]
Is getting the query key exposed in the public API? Since the `tanstack v5` seems to only have usable API for invalidating APIs using the keys.   (I am aware that I can construct it via the name of service/ method, params, but I have a bad feeling renaming something will cause unfortunate bugs, I'd prefer to keep it typesafe and automatic)

**Comment by srikrsna-buf** [comment]
Hey! You can use [this](https://github.com/connectrpc/connect-query-es?tab=readme-ov-file#connectquerykey) to get the query key

**Comment by Nikola-Milovic** [comment]
Sorry @srikrsna-buf, do you have an example usage? I am aware of it, but haven't figured out how the type helps me exactly

**Comment by timostamm** [comment]
Hey Nikola, here's an example with [createConnectQueryKey](https://github.com/connectrpc/connect-query-es?tab=readme-ov-file#createconnectquerykey) of the recently released v1:

```ts
import { createConnectQueryKey } from "@connectrpc/connect-query";
import { say } from "./gen/eliza-ElizaService_connectquery";

// ["connectrpc.eliza.v1.ElizaService", "Say"]
const partialKey = createConnectQueryKey(say);

// ["connectrpc.eliza.v1.ElizaService", "Say", { id: "0fdf2ebe-9a0c-4366-9772-cfb21346c3f9" } ]
const specificKey = createConnectQueryKey(say, { sentence: "hello" });
```

The first key refers to all calls to the `Say` RPC. The second key refers to a specific call by providing a request object.

With earlier versions, you would call `say.getQueryKey()`.

**Comment by Nikola-Milovic** [comment]
Yeah, updating to v1 is going to resolve this! :+1:
