### ISSUE TITLE
How do you get queryKey for Infinit queries 

### ISSUE THREAD

**Issue by acbeni** [connectrpc/connect-query-es#304]
Hello There, 

I'm trying to migrate to version 1.0.0 of `connect-query-es` and one issue i stumbled upon is how do i get the query key for an infinit query. I've already noticed `createConnectQueryKey` for a normal query key, but i don't know how it can be adapted to infinit queries. Or maybe expose a method such as `createInfinitConnectQueryKey` if something similar doesn't exist.

Thanks in advance

**Comment by paul-sachs** [comment]
`createConnectQueryKey` should be sufficient to get the query key for an infiniteQuery as well as a regular query. For example, if you were to use the following hook:

```tsx
const query = useInfiniteQuery(
  methodDescriptor,
  {
    token: "token",
    page: 0n,
  },
  {
    getNextPageParam: (lastPage) => lastPage.page + 1n,
    pageParamKey: "page",
  }
);
```

You can get that set data with something like:

```tsx
const data = await queryClient.getQueryData(
  createConnectQueryKey(methodDescriptor, { token: "token" })
);
```

Does that answer your question? I think we can add more details to the docs indicating this behaviour for sure.

**Comment by acbeni** [comment]
Ah i see how the key is created, then in this case `createProtobufSafeUpdater` should have a variant that updates an `InfinitData`  since in its current form it updates only a message.

Just to give a code example
```ts
 queryClient.setQueryData(
        createConnectQueryKey(listCars,{carId}),
        createProtobufSafeUpdater(listCars, (prev) => {
            ....
```
the `createProtobufSafeUpdater` signature accepts a Message type, so in its current form i see no way in using it for InfinitData as a param

**Comment by paul-sachs** [comment]
Yes, `createProtobufSafeUpdater` is more of a primitive to work with basic data, infinite data will need another wrapper to work around. We avoided creating more helpers for this because it becomes increasingly opinionated and we didn't want to narrow too much. You should be able to make your own with something like:

```tsx
queryClient.setQueryData(
  createConnectQueryKey(listCars,{carId}),
  (data: InifiniteData<typeof listCards.O>) => {
    return {
          pageParams: [...data.pageParams, 1n],
          pages: [
            ...data.pages,
            createProtobufSafeUpdater(listCards, {
              page: 1n,
              items: ["1 Item", "2 Item", "3 Item"],
            })(),
          ],
        };
  }
);
```

The above example just pushes a new page on (i didn't know what Cars looked like so i just used strings). Admittedly, this API is not the best designed for this. Thankfully, the API is flexible enough to work anywhere.

**Comment by acbeni** [comment]
Thats makes sense, seems like a reasonable solution.

Thank you for your support, and keep up the good work guys 🚀 
You are the best 👍
