### ISSUE TITLE
Export `createUseQueryOptions` and `createUseInfiniteQueryOptions` from the library

### ISSUE THREAD

**Issue by lsmurray** [connectrpc/connect-query-es#327]
First off, thank you for all the work you've put into this package!

I would like to propose some use cases for `createUseQueryOptions` and `createUseInfiniteQueryOptions` as a continuation of the conversation from https://github.com/connectrpc/connect-query-es/issues/296.

```ts
// fetching a list of suspense queries
const suspenseQueries = useSuspenseQueries({
  queries: userIds.map((userId) =>
    createUseQueryOptions(getUser, { userId }, { transport })
  ),
});

// fetching a list of standard queries
const queries = useQueries({
  queries: userIds.map((userId) =>
    createUseQueryOptions(getUser, { userId }, { transport })
  ),
});

// ensuring a query is loaded
await queryClient.ensureQueryData(
  createUseQueryOptions(getUser, { userId: 1 }, { transport })
);

// prefetching a query
queryClient.prefetchQuery(
  createUseQueryOptions(getUser, { userId: 1 }, { transport })
);
```

So far I do not have a use case for `createUseInfiniteQueryOptions` but other people may need `createUseInfiniteQueryOptions` for these same use cases, specifically prefetching and ensuring a query is loaded.

I can use `createConnectQueryKey` and `callUnaryMethod` to build my own `createUseQueryOptions` but once I've made that code typesafe and reusable its basically a copy of the internal methods.

**Comment by paul-sachs** [comment]
Let's keep the conversation within the original issue of #296 to keep things focused. It may turn out to make sense to expose these APIs but I'd like to keep the discussion in one place.

**Comment by paul-sachs** [comment]
After further discussions with the team, we've decided to reexport `createQueryOptions` and `createInfiniteQueryOptions`. I feel like we'll definitely want a more opinionated `useQueries` and other APIs but if this unblocks users, then it's valuable. It'll be available in the next release.

**Comment by lsmurray** [comment]
thank you - I had rewritten both in my project. Really appreciate it and looking forward to the more opinionated APIs when they are available!
