### ISSUE TITLE
Very easy to create collisions between infinite and non-infinite queries

### ISSUE THREAD

**Issue by lsmurray** [connectrpc/connect-query-es#328]
It is very easy for users to create collisions between infinite and non-infinite queries.

Consider a list API where we use token based pagination. The token is a string and an empty token means we want the first page.
I may call the API with `useQuery` and no `page_token` to get a couple results from the first page.
I may also call the API with `useInfiniteQuery` and a `page_token` for an infinite list of results.
The issue is both these calls produce an identical query key.

You can see why here... the connect code sets `page_token` to `undefined` for infinite query results.

https://github.com/connectrpc/connect-query-es/blob/639d4a529f236a50568021aa4a3db4b0d0dc0105/packages/connect-query/src/create-use-infinite-query-options.ts#L163

Example Proto

```proto
rpc ListUsers(ListUsersRequest) returns (...) {

}

message ListUsersRequest {
  optional string page_token = 1;
}
```

Example keys that are created

```ts
import { hashKey } from "@tanstack/react-query";
const useQueryKey = createConnectQueryKey(listUsers, {
  pageSize: 10,
});

const useInfiniteQueryKey = createConnectQueryKey(listUsers, {
  pageSize: 10,
  pageToken: undefined,
});

console.log(hashKey(useQueryKey) === hashKey(useInfiniteQueryKey))
// true
```

I'm not sure if there is a good solution for this but if there is it should be documented. For now one option is to manually check that every time I call `useQuery` I pass a `page_token` and set it to an empty string.

**Comment by paul-sachs** [comment]
Hmm, this is true. Thanks for bringing this to our attention. I think something that we could consider is having `useInfiniteQuery` use a modified query key, with a trailing parameter to indicate it's for infinite query only. I'll need to investigate the ramifications of that. Since our query keys are all arrays, invalidating should still match without the trailing key, but I'll need to build up some tests to make sure that's the case.

**Comment by timostamm** [comment]
In TanStack Query, query keys are completely up to the user. 

Are there any use cases where you would _want_ to share a cache between an infinite query and a non-infinite query? Or use cases where you would want to use exactly the same RPC, but with _different_ caches?

**Comment by timostamm** [comment]
> Since our query keys are all arrays, invalidating should still match without the trailing key, but I'll need to build up some tests to make sure that's the case.

I'd also expect a query key to invalidate an infinite query that uses the same key with a trailing parameter. Did your tests confirm that, @paul-sachs?

**Comment by lsmurray** [comment]
thanks for the help, a trailing parameter sounds like a reasonable solution and everything @paul-sachs mentioned in the previous comment sounds accurate to me.

**Comment by paul-sachs** [comment]
Fixed in https://github.com/connectrpc/connect-query-es/releases/tag/v1.2.0
