### ISSUE TITLE
useQueries with current setup

### ISSUE THREAD

**Issue by malinskibeniamin** [connectrpc/connect-query-es#333]
Hi there!

https://github.com/connectrpc/connect-query-es/issues/67 has previously mentioned using `createQueryOptions` to allow `useQueries` to work, however that was an issue prior to v1 being released.

With the current version of the connect library, what would be the best example to follow to apply `useQueries`?

I imagine `useQueries` types within `@connectrpc/connect-query` would have to match with `@tanstack/react-query`. Is there any other blocker from the architecture perspective that might not allow `useQueries`, for example using more than 1 transport?

**Comment by ivanvanderbyl** [comment]
I'm also blocked on this, I just began an upgrade from 0.6.0 to 1.2.0 and realised there wasn't an easy way to do `useQueries`

**Comment by ivanvanderbyl** [comment]
I was eventually able to get my previous behaviour by porting the createQueryOptions helper back:

```ts
import { Message, PartialMessage } from '@bufbuild/protobuf'
import { CallOptions, ConnectError, Transport } from '@connectrpc/connect'
import {
	ConnectQueryKey,
	DisableQuery,
	MethodUnaryDescriptor,
	callUnaryMethod,
	createConnectQueryKey,
} from '@connectrpc/connect-query'
import { QueryFunctionContext } from '@tanstack/react-query'

export function createQueryOptions<I extends Message<I>, O extends Message<O>>(
	methodDescriptor: Pick<MethodUnaryDescriptor<I, O>, 'I' | 'O' | 'kind' | 'name' | 'service'>,
	input: DisableQuery | PartialMessage<I> | undefined,
	{
		callOptions,
		transport,
	}: {
		transport: Transport
		callOptions?: CallOptions | undefined
	}
): {
	enabled: boolean
	queryKey: ConnectQueryKey<I>
	queryFn: (context?: QueryFunctionContext<ConnectQueryKey<I>>) => Promise<O>
	// placeholderData?: () => O | undefined;
	/**
	 * We never actually return a throwOnError, we just use this to allow
	 * @tanstack/query to infer the error types we CAN throw.
	 */
	throwOnError?: (error: ConnectError) => boolean
} {
	return {
		enabled: true,
		queryKey: createConnectQueryKey(methodDescriptor, input),
		queryFn: () => callUnaryMethod(methodDescriptor, input as PartialMessage<I>, { callOptions, transport }),
	}
}
```
