### ISSUE TITLE
`enabled` param is not taken into consideration with infinitqueries

### ISSUE THREAD

**Issue by acbeni** [connectrpc/connect-query-es#336]
Hi, There was an issue about `enabled` param not working in useQuery that seems to have been fixed in [this commit](https://github.com/connectrpc/connect-query-es/commit/6ea7570b2975f8fb700951dad14d5c39949da179), unfortinatenly the problem still persist at `useInfinitQuery` and also headers provided to useInfinitQuery dont seem to be sent, but maybe the issues are related.

Can yo check this issue please

**Comment by paul-sachs** [comment]
Yeah looks like I forgot to port that to useInfiniteQuery. Will submit a fix shortly. In the meantime, you can use the 'disableQuery' symbol as the input to that api. 

Regarding headers not being passed through, how are you passing the headers in?

**Comment by acbeni** [comment]
As for the headers, i think it was just due to the disable param not being considered. Since the  query is supposed to be enabled only after some auth headers are computed. Thats why i didnt find them in the logs. So the headers are fine i think. Its just the disabled param that needs fixing 👍

**Comment by acbeni** [comment]
Thank you @paul-sachs for the fast action 🎉🎉🎉 , any rough estimate on where this will be released ?

**Comment by paul-sachs** [comment]
Should be able to get to a release later today. Just trying to nail down if a previous change warrants a 2.0 since it changed the queryKey used by infiniteQuery.

**Comment by acbeni** [comment]
Awesome 😎, thank you very much @paul-sachs 🙏

**Comment by paul-sachs** [comment]
Fixed in https://github.com/connectrpc/connect-query-es/releases/tag/v1.2.0
