### ISSUE TITLE
useInfiniteQuery types does not validate query parameters when pageParamKey is provided

### ISSUE THREAD

**Issue by andriuss** [connectrpc/connect-query-es#342]
There is no type error in this example when passing **notExistingField** to query:
<img width="629" alt="Screenshot 2024-02-15 at 11 39 25" src="https://github.com/connectrpc/connect-query-es/assets/6738026/c9d02aea-3f89-42ba-9275-a1f93cdb8ee8">

Commenting out **pagePrameKey: 'cursor'** or not passing default value for cursor gives correct check for query params:
<img width="703" alt="Screenshot 2024-02-15 at 11 40 49" src="https://github.com/connectrpc/connect-query-es/assets/6738026/924f5938-89a4-4513-9480-9708ebfe764e">

<img width="629" alt="Screenshot 2024-02-15 at 11 42 19" src="https://github.com/connectrpc/connect-query-es/assets/6738026/3bff3716-ddc1-4947-b239-baec18279771">

**Comment by paul-sachs** [comment]
Hmm, I'll need to dig into this one when I have some time. We are doing a bunch of inference and making sure the cursor be a required param so it's probably losing some restrictions somewhere in the mix.

**Comment by paul-sachs** [comment]
Fixed in https://github.com/connectrpc/connect-query-es/releases/tag/v1.3.0
