### ISSUE TITLE
Buf Contributor License Agreement link is broken

### ISSUE THREAD

**Issue by alexongh** [connectrpc/connect-query-es#386]
The link at [.github/CONTRIBUTING.md](https://github.com/connectrpc/connect-query-es/blob/main/.github/CONTRIBUTING.md) titled `Buf's Contributor License Agreement` is broken.

Currently, it is linking to the following URL: https://cla-assistant.io/connectrpc/connect-query-es

Which displays the following error:

![2024-07-09_00-34](https://github.com/connectrpc/connect-query-es/assets/42301971/4a579c15-3edc-41ed-8bb1-d6d9b050e737)

![2024-07-09_00-35](https://github.com/connectrpc/connect-query-es/assets/42301971/1fe8502d-86dc-4cfc-861e-f50f3402cd39)

**Comment by perezd** [comment]
Thanks for catching that. In fact, this CLA needs to be replaced with our CNCF setup.

**Comment by drice-buf** [comment]
I'll make the changes once I have the necessary repo permissions.

**Comment by drice-buf** [comment]
Fixes across all connect repos:

https://github.com/connectrpc/authn-go/pull/15
https://github.com/connectrpc/conformance/pull/900
https://github.com/connectrpc/connect-dart/pull/6
https://github.com/connectrpc/connect-es/pull/1136
https://github.com/connectrpc/connect-go/pull/765
https://github.com/connectrpc/connect-kotlin/pull/298
https://github.com/connectrpc/connect-playwright-es/pull/146
https://github.com/connectrpc/connect-query-es/pull/388
https://github.com/connectrpc/connect-swift/pull/279
https://github.com/connectrpc/connectrpc.com/pull/184
https://github.com/connectrpc/envoy-demo/pull/20
https://github.com/connectrpc/examples-es/pull/1707
https://github.com/connectrpc/examples-go/pull/180
https://github.com/connectrpc/grpchealth-go/pull/70
https://github.com/connectrpc/grpcreflect-go/pull/76
https://github.com/connectrpc/otelconnect-go/pull/178
https://github.com/connectrpc/validate-go/pull/22
https://github.com/connectrpc/vanguard-go/pull/129
