### ISSUE TITLE
Add way to provider updater types to queryclient.setQueryData with createConnectQueryKey

### ISSUE THREAD

**Issue by nickzelei** [connectrpc/connect-query-es#391]
Hey all, I'm playing with the `createConnectQueryKey` and I'm wondering if there is a way to allow TS to better infer the return type when using it in conjunction with the tanstack `queryclient.setQueryData`.

It's able to infer the some of the types, but not all of them. Arguably the most important being the actual value that the cache is going to be updated to.

Screenshot below shows an example. TS is definitely inferring some of the types, but the `updater` is still set to `unknown`. 
It would be awesome if by passing in the query key if the `updater` could be set to the response type, in this case, `GetAccountOnboardingConfigResponse`

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/f8053613-e72c-4038-a189-7969eb840b5f">

**Comment by timostamm** [comment]
I don't think TanStack's `QueryClient.setQueryData` - which we are using here - can infer data type from the key type. To enforce matching key and value, we'd have to provide our own API to set query data.
