### ISSUE TITLE
Query keys with dynamic transports

### ISSUE THREAD

**Issue by Victor-Mestre-Sybo** [connectrpc/connect-query-es#418]
Hello, first of all thanks for this amazing project!
We have this setup where our transport contains dynamic parameters, for example:
```
const transport = createConnectTransport({
  baseUrl: `/api/accounts/${accountId}/services`
})
```
So we have this issue where, when switching `accountId` the same cache will be used for a given query since the query key does not contain any information about the transport. We have considered either making our own abstraction of `useQuery` or calling something like `queryClient.removeQueries()` when the transport's baseUrl changes, is there any better alternative (like including this information in the query key)?

**Comment by timostamm** [comment]
Thanks for filing the issue, Victor. `callOptions` are also not part of the query key.

The best workaround is probably to call `createUseQueryOptions`, modify the query key, and pass the options to `useQuery` from `@tanstack/react-query`.

**Comment by timostamm** [comment]
With #437, we can make the Transport part of the query key. It will be important to create the transport in a module scope, or to memoize it. For example:

```ts
const transport = useMemo(() => createConnectTransport({
  baseUrl: `/api/accounts/${accountId}/services`,
}), [accountId]);

useQuery(say, {sentence: "hi"}, {transport});
```

Could be a footgun, but having to keeping track of reference is common in react.

**Comment by Victor-Mestre-Sybo** [comment]
Thank you for your suggestions! 
@timostamm in order to address this issue using the new `createTransportKey` method, I'd still need to call `createUseQueryOptions` and modify the queryKey by prepending the transport key right?

**Comment by Victor-Mestre-Sybo** [comment]
Sorry, I don't really understand it, I guess I'm missing something. How does `createTransportKey` come into play in your proposed solution? 

As far as I understand, by doing `useQuery(say, {sentence: "hi"}, {transport});` , even if a new transport is created, the query key does not depend on the transport, since this is what is used under the hood:
`const queryKey = createConnectQueryKey(methodSig, input);`

Therefore, the cache will be the same for a given key even after changing the transport right?

**Comment by timostamm** [comment]
@Victor-Mestre-Sybo, this PR wires it up: https://github.com/connectrpc/connect-query-es/pull/441

**Comment by Victor-Mestre-Sybo** [comment]
@timostamm now it makes sense! it's looking really promising, thank you so much for addressing this issue!

**Comment by timostamm** [comment]
@paul-sachs raised a good point: For SSR, you want to populate the query cache on the server, then use the that cache in the web browser (you prefetch queries, dehydrate the query client, and hydrate it again). For that to work, query keys must be the same on the server and in the web browser, which isn't guaranteed with createTransportKey (it counts references).

We're adding an escape hatch for SSR with #444.

We'll get a pre-release version 2 out as soon as possible, which solves this issue. Closing it.

**Comment by Victor-Mestre-Sybo** [comment]
Thanks again! Regarding the issue you mention with SSR, it would have been helpful that the `Transport` object created with `createConnectTransport` method from `@connectrpc/connect-web` contained some unique parameter like the `baseUrl` itself. This way it could have been used as key, guaranteeing both uniqueness and same value in client and server. Just a thought.

**Comment by timostamm** [comment]
We considered it. The transports from `@connectrpc/connect-web` also support interceptors, which can make arbitrary changes that affect caching. It isn't feasible to create a unique key.
