### ISSUE TITLE
npm script "preview" in example seems outdated

### ISSUE THREAD

**Issue by timostamm** [connectrpc/connect-query-es#442]
```bash
$ pnpm install
$ pnpm run build
$ cd examples/react/basic 
$ pnpm run preview
error when starting preview server:
Error: The directory "dist" does not exist. Did you build your project?
```

Perhaps we should add a "build" script, or simply remove this script? `pnpm run dev` works as expected.

**Comment by paul-sachs** [comment]
Removing it makes sense. Our samples shouldn't be used as templates for full applications anyways, just as live usage examples.
