### ISSUE TITLE
Mocking the RPC for Storybook

### ISSUE THREAD

**Issue by p3yman** [connectrpc/connect-query-es#455]
Hello, 

I was looking into the docs to see how I can mock the RPC for Storybook and the docs seem old (maybe for the 0.13 version?) as it says to import `SomeService` and use it with `createRouterTransport` but I don't have generated is something like this:

```ts
export const getPage = {
  localName: "getPage",
  name: "GetPage",
  kind: MethodKind.Unary,
  I: GetPageRequest,
  O: GetPageResponse,
  service: {
    typeName: "lab.v1.Service"
  }
} as const;
```

The `createRouterTransport` still has the same definition for having `typeName` and `methods` but maybe something is wrong from my side.

Just for more context, I'm generating from our backend in Go and trying to mock it in our frontend repo in React using Tanstack.

Can someone help me with this? What I want in the end is to be able to create different mocks for different stories but a head start also would be good to see how to mock with the 1.* versions.

Appreciate all the hard work, amazing package, and amazing support ❤️

**Comment by timostamm** [comment]
Hey Peyman, you'll need to install [@connectrpc/protoc-gen-connect-es](https://www.npmjs.com/package/@connectrpc/protoc-gen-connect-es), and add the plugin to your `buf.gen.yaml` file. It will generate `_connect.ts` files with the services that you can use with `createRouterTransport`.

**Comment by timostamm** [comment]
Closing, but please feel free to comment!
