### ISSUE TITLE
Need ability to transform mutation responses

### ISSUE THREAD

**Issue by sbussard** [connectrpc/connect-query-es#460]
Hi, this library rocks! 

I'd like a way to transform responses from the api for both mutations and queries. 
For `useQuery`, the `select` option seems sufficient, but it looks like nothing similar exists for `useMutation`. 

The reason why this important to me is that the rpc responses include a response field which is oneof data or error.
I need to add logic to all of these hooks to check for errors so that I don't have to copy and paste the same logic over and over all over the codebase. 

Thanks!

**Comment by sbussard** [comment]
It seems like this lack of customization comes from @tanstack/react-query, but the other approach I was thinking was to wrap the query/mutation function itself, but this library doesn't expose the query/mutation function (with good reason) so I'm stuck and thus this issue.

**Comment by paul-sachs** [comment]
So this actually can be done by just combining two `useMutation` calls, and it would look something like:

```ts
import { useMutation as useTanstackMutation } from "@tanstack/react-query";
import { useMutation } from "@connectrpc/connect-query";

...
const baseMutation = useMutation(someMethodDesc);
const otherMutation = useTanstackMutation((input: WhateverInput) => {
  const result = await baseMutation.mutateAsync(input); 
  //... do whatever here for intermediary
});
```

You can also use `callUnaryMethod` directly if you want to, and make something without `useMutation` from connect entirely.

Things get more complicated with typescript generics. We use something like the following internally that allows some reasonable amount of flexibility:

```ts
/**
 * A utility function that allows you to enhance a mutation to create a custom mutation
 * with different input and output types.
 */
export function useMutationWithCustomFn<
  FnI,
  FnO,
  I extends Message<I>,
  O extends Message<O>,
  Ctx = unknown,
>(
  methodSignature: MethodUnaryDescriptor<I, O>,
  fn: (
    input: FnI,
    original: UseMutateAsyncFunction<
      O,
      ConnectError,
      PartialMessage<I>,
      unknown
    >
  ) => Promise<FnO> | FnO,
  options?: Omit<
    UseMutationOptions<FnO, ConnectError, FnI, Ctx>,
    "mutationFn"
  > & {
    transport?: Transport;
  }
) {
  const baseMutation = useMutation(methodSignature, {
    transport: options?.transport,
  });
  return tsUseMutation({
    ...options,
    mutationFn: (variables: FnI) => {
      // TODO: Add fallback logic after https://github.com/connectrpc/connect-query-es/pull/359 gets merged
      const result = fn(variables, baseMutation.mutateAsync as any);
      if (result instanceof Promise) {
        return result;
      }
      return Promise.resolve(result);
    },
  });
}
```

The types aren't perfect and it'll change a bit with v2, which is partly why this isn't published, but it gives you an idea.

**Comment by sbussard** [comment]
Thank you so much for your response @paul-sachs! 

This issue is now considered solved because there's (1) awareness, (2) discoverability for others, and (3) a good solution to the problem. Great work! Closing.
