### ISSUE TITLE
is a question about version upgrade `0.5.3` => `1.4.2`. (To be closed)

### ISSUE THREAD

**Issue by Lennon57** [connectrpc/connect-query-es#462]
We're making good use of that library in our products. Thank you for creating a great library.
I am trying to upgrade from version 0.5.3 to the latest version 1.4.2. Are there any expected problems?

**Comment by paul-sachs** [comment]
Hi @Lennon57. The changes from 0.x and 1.x are relatively quite large. In 0.x, we were just providing options to react-query, and in 1.x we are actively wrapping all calls to react-query apis. Also, 0.5.3 was built around react-query@4.x, where 1.x requires react-query@5.x. As a result, migration is non-trivial.

**Comment by paul-sachs** [comment]
Closing for now unless there are any follow up questions or concerns.
