### ISSUE TITLE
NPM package for @connectrpc/connect-query-core is hidden?

### ISSUE THREAD

**Issue by pwalker** [connectrpc/connect-query-es#481]
I'm trying to take a look at the latest rc.3, and I ran into an error when I tried to pnpm install the packages.

``` 
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@connectrpc%2Fconnect-query-core: Not Found - 404

This error happened while installing the dependencies of @connectrpc/connect-query@2.0.0-rc.3

@connectrpc/connect-query-core is not in the npm registry, or you have no permission to fetch it.
```

And when I search for it the package also isn't visible: https://www.npmjs.com/search?q=%40connectrpc%2Fconnect-query-core

I'm just curious, is it possible to make this public? I know the 2.0.0-rc.3 was recently released, so I'm assuming that maybe it was missed?

**Comment by plunkettscott** [comment]
Encountering the same issue here

**Comment by timostamm** [comment]
Apologies. When a new package is published, it's private by default. It should be public now. https://www.npmjs.com/package/@connectrpc/connect-query-core
