### ISSUE TITLE
Support cacheable rpcs with tanstack query 

### ISSUE THREAD

**Issue by StarpTech** [connectrpc/connect-query-es#62]
**Is your feature request related to a problem? Please describe.**

See https://buf.build/blog/introducing-connect-cacheable-rpcs/ when using in combination with `@tanstack/react-query` `GET` is not used properly

```ts
export const transport = createConnectTransport({
  baseUrl: "...",
  useHttpGet: true,
});

return (
    <>
      <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
        <TransportProvider transport={transport}>
          <QueryClientProvider client={queryClient}>
            <AppProvider>
              <Toaster />
              {getLayout(<Component {...pageProps} />)}
            </AppProvider>
          </QueryClientProvider>
        </TransportProvider>
      </ThemeProvider>
    </>
  );
```

```proto
 rpc GetAnalyticsView(GetAnalyticsViewRequest) returns (GetAnalyticsViewResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
```

**Comment by timostamm** [comment]
Hey @StarpTech, I've moved the issue from connect-es to connect-query, which seems to be to right place for this issue.

Can you provide details about the problem? Do you not see a GET request in the browser, or is it something else?

**Comment by StarpTech** [comment]
> Can you provide details about the problem? Do you not see a GET request in the browser, or is it something else?

Exactly, it's still a POST request.
